// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://doucxeoyrhehujdymlrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvdWN4ZW95cmhlaHVqZHltbHJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTc0NjUsImV4cCI6MjA2NTQ5MzQ2NX0.svyF2D1Fu5NhRQcqsms-lHf5GvgVVmpKcf3yagQ3hlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);